add build target

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -34,9 +34,25 @@ jobs:
       - run: make test
       - *save_cache
 
+  build:
+    executor:
+      name: default
+    steps:
+      - checkout
+      - *restore_cache
+      - run: make build
+      - run: |
+        if [[ `git status <<parameters.path>> --porcelain` ]]; then
+          echo "ERROR: uncommitted changes"
+          git status --porcelain
+          exit 1
+        fi
+      - *save_cache
+
 workflows:
   version: 2
   ci:
     jobs:
       - lint
       - test
+      - build
